# H2 Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pet_store

    username: sasg
    password: 1234

# Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
